language: python
python:
  - "3.9"
cache: pip
services: 
- "postgresql"
install:
- pip install -r requirements.txt
branches:
  only: 
    - staging
env: DJANGO_SETTINGS_MODULE='purbeurre.settings.travis'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- python manage.py collectstatic --noinput
- pytest